### ISSUE TITLE
Feat: Accept MongoDB connection as a parameter

### ISSUE THREAD

**Issue by aerabi** [aerabi/mongo-ci#1]
The functions `load`, `drop`, and `deleteAll` create a new connection to the database and then use it. As an optional argument, we should accept the database connection, to avoid making an unnecessary amount of new connections.

**Comment by zinovik** [comment]
Could you check my PR: https://github.com/aerabi/mongo-ci/pull/4?

**Comment by aerabi** [comment]
Closed through #4
